### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FlorianWendelborn** [sonewman/simple-child#1]
Hi, I think I want to use this project for a project of mine. Is there any way you could include a LICENSE? If you don't care about which one I'd recommend the MIT License.

**Comment by sonewman** [comment]
I'm sorry for the very delayed response. MIT is fine, I usually use that. I must have just forgot.

**Comment by sonewman** [comment]
OK done as of 8f861be28571d600355d0c67d3dffee570e9ecdc
